"""Render an index's pipeline files from its committed policy.

Three mechanisms, each small, each with a reason it cannot be smaller:

**A header contract.** Every rendered file's first line names this tool and a
version. That line — not a filename, not a directory listing — is what makes a
file "ours": it is what `--check` drift-tests, what pin carry-forward scrapes,
and what tells an operator the file is not theirs to edit. A file whose header
names a *newer* version than this tool is refused rather than overwritten; the
operator's bot is older than whatever last rendered it, and silently
downgrading their pipeline is the one outcome worse than doing nothing.

**Pin carry-forward.** The templates ship a default SHA for every action they
use, but a live repository's Dependabot/Renovate bumps those, and a render that
reset them would undo the bump on every run. So the committed files are scraped
first and an action pinned identically everywhere it appears is carried
forward. A ref that is *not* a 40-hex commit SHA is never carried: this
generator emits the workflows the "SHA-pinned actions" invariant governs, so a
hand-edit to `@main` must not survive a render as the new pin.

**Line-level placeholder substitution.** `{{key}}`, never GitHub's `${{ … }}`
— hence the `$` lookbehind. A placeholder alone on a line whose value is empty
takes the whole line with it, which is how an optional step or an entire
optional job disappears without a second template.
"""

from __future__ import annotations

import re
from importlib import resources
from typing import TYPE_CHECKING, Final

from ocx_indexbot.core.policy import IndexPolicy, resolves_at_runtime
from ocx_indexbot.errors import ValidationError

if TYPE_CHECKING:
    from collections.abc import Mapping

TOOL_HEADER_VERSION: Final[int] = 1
"""Bump only when the render/scrape contract changes in a way this tool could
no longer safely parse in an older file. The number in the line changes; the
pattern never does, which is why nothing below branches per version."""

HEADER_LINE: Final[str] = f"# generated by indexbot ci v{TOOL_HEADER_VERSION} — do not edit"

_HEADER_RE: Final[re.Pattern[str]] = re.compile(r"^# generated by indexbot ci v(\d+) — do not edit")

_PLACEHOLDER: Final[re.Pattern[str]] = re.compile(r"(?<!\$)\{\{\s*([a-z_]\w*)\s*\}\}")
_LINE_PLACEHOLDER: Final[re.Pattern[str]] = re.compile(r"^[ \t]*\{\{\s*([a-z_]\w*)\s*\}\}[ \t]*$")

_USES_LINE: Final[re.Pattern[str]] = re.compile(
    r"^([ \t]*(?:-[ \t]+)?uses:[ \t]*)([^@\s]+)@([^\s#]+)([ \t]*#[^\n]*)?$", re.MULTILINE
)
_COMMIT_SHA: Final[re.Pattern[str]] = re.compile(r"^[0-9a-f]{40}$")

GITHUB_DIR: Final[str] = ".github/workflows"
GITLAB_FILE: Final[str] = ".gitlab-ci/indexbot.yml"

DEFAULT_GITLAB_IMAGE: Final[str] = (
    # ghcr.io/astral-sh/uv:python3.13-alpine, resolved 2026-08-25
    "ghcr.io/astral-sh/uv@sha256:81285c44b0ed162841eb91d3e6671dd6e63960b86ef47dcbe34d4a9418112175"
)
"""What a GitLab job runs in when `ci.setup` says nothing. `uv` is the one
thing every `ci.run` default needs, and this image is the smallest way to
have it.

**Pinned by digest, never by tag**, for the reason WF-02 pins every GitHub
`uses:` to a commit SHA. `indexbot-governance-poll` is the one generated
GitLab job holding `$GITLAB_TOKEN` — `api` scope, so it can label, comment and
merge — and it runs in this image. A tag is a mutable pointer its publisher
can move under a deployment that never changed a line of its own pipeline,
which is the whole of what SHA-pinning exists to stop; a registry host in the
G-03 allowlist is not a reason to accept that, because the allowlist governs
where package CONTENT may live and says nothing about what the privileged job
executes.

The tag it was resolved from is in the comment above, so a human can see what
is pinned and bump it deliberately. This is an image-INDEX digest rather than
a per-platform manifest digest, so it still resolves on whatever architecture
the runner happens to be. A deployment that would rather track a tag, or run
its own image, says so in `ci.setup` and owns that choice.
"""

_GITHUB_FILES: Final[tuple[str, ...]] = (
    "validate.yml",
    "governance.yml",
    "reconcile.yml",
    "pr-checks-label.yml",
    "stale.yml",
)


def parse_header_version(first_line: str) -> int | None:
    """The version a file's header names, or `None` when it has no header at
    all — which the caller must read as "not ours": never drift-checked, never
    scraped, never overwritten."""
    match = _HEADER_RE.match(first_line)
    return None if match is None else int(match.group(1))


def _template(relpath: str) -> str:
    resource = resources.files("ocx_indexbot.ci").joinpath(f"templates/{relpath}")
    return resource.read_text(encoding="utf-8")


def render_string(template: str, variables: Mapping[str, str]) -> str:
    """Substitute every `{{key}}` in `template`.

    A line that is nothing but a placeholder whose value is empty is dropped
    entirely, so an optional step leaves no blank line and an optional job
    leaves no orphaned separator. An unknown key raises rather than surviving
    into output — a template referencing a variable no caller supplies is
    always a bug in this package, never something to render literally.
    """

    def _value(key: str) -> str:
        if key not in variables:
            raise ValidationError(f"ci template references unknown placeholder {{{{{key}}}}}")
        return variables[key]

    kept: list[str] = []
    for line in template.split("\n"):
        whole = _LINE_PLACEHOLDER.match(line)
        if whole is not None and not _value(whole.group(1)):
            continue
        kept.append(_PLACEHOLDER.sub(lambda m: _value(m.group(1)), line))
    return "\n".join(kept)


def scrape_pins(contents: Mapping[str, str]) -> dict[str, str]:
    """Action name -> the `ref` (plus its verbatim trailing comment) to carry
    forward.

    An action is carried only when every `uses:` of it, across every file,
    agrees on one commit SHA. Two files disagreeing means there is no single
    answer, and a non-SHA ref anywhere means the pin was hand-edited to
    something mutable — in both cases the template's own default wins, which
    is the only outcome that cannot quietly widen what the pipeline runs.

    Agreement is on the **ref**, never on the trailing `# vX.Y.Z` comment.
    Real repositories carry the same SHA with one space before the comment in
    one file and two in another, and treating that as two different pins would
    silently reset an action every render — the exact bump-reverting bug pin
    carry-forward exists to prevent. The comment is cosmetic, so the
    first-seen spelling of it is carried along with the ref.
    """
    refs: dict[str, set[str]] = {}
    comments: dict[str, str] = {}
    mutable: set[str] = set()
    for text in contents.values():
        for match in _USES_LINE.finditer(text):
            name, ref, comment = match.group(2), match.group(3), match.group(4) or ""
            if _COMMIT_SHA.fullmatch(ref) is None:
                mutable.add(name)
                continue
            refs.setdefault(name, set()).add(ref)
            comments.setdefault(f"{name}@{ref}", comment)
    return {
        name: f"{ref}{comments[f'{name}@{ref}']}"
        for name, found in refs.items()
        if len(found) == 1 and name not in mutable
        for ref in found
    }


def apply_pins(text: str, pins: Mapping[str, str]) -> str:
    """Rewrite each `uses: <action>@<default>` to the carried-forward pin."""

    def _rewrite(match: re.Match[str]) -> str:
        prefix, name = match.group(1), match.group(2)
        carried = pins.get(name)
        return match.group(0) if carried is None else f"{prefix}{name}@{carried}"

    return _USES_LINE.sub(_rewrite, text)


def normalize_for_drift(text: str) -> str:
    """What `--check` compares.

    The header line is stripped unconditionally — a version bump there is
    this tool moving, never a deployment change. A `uses:` ref is replaced
    with a fixed `@<pinned>` placeholder only when it is a 40-hex commit SHA:
    the deployment's own dependency bot re-pinning to a new SHA is not drift.
    Any other ref is left verbatim, because that is exactly the case this
    gate exists to catch — a pinned action hand-edited down to a mutable ref
    (`@main`, `@v4`) must compare unequal, not disappear alongside the
    legitimate re-pins. Everything else — a changed trigger, a widened
    permission, an edited pathspec — is exactly what must be caught too.

    The placeholder carries the action name AND the fact that a ref was
    there at all — it used to drop the `@ref` outright, down to a bare
    `uses: owner/repo`. That bare form is indistinguishable from `_USES_LINE`
    simply not matching a line at all: `owner/repo` with no `@` — an action
    stripped of its pin entirely, not merely re-pinned to a different SHA —
    fails to match (`@` is not optional in the regex) and passes through
    untouched, landing on the *exact same* bare text a valid pin blanks down
    to. So a hand-edit that deletes a pin outright used to normalize equal to
    the correctly-pinned line it replaced, in the one job that now runs with
    `contents: write`. `@<pinned>` cannot collide with an untouched,
    never-pinned line, because nothing untouched ever contains it.
    """

    def _blank_pinned_ref(match: re.Match[str]) -> str:
        if _COMMIT_SHA.fullmatch(match.group(3)) is None:
            return match.group(0)
        return f"{match.group(1)}{match.group(2)}@<pinned>"

    without_refs = _USES_LINE.sub(_blank_pinned_ref, text)
    lines = without_refs.split("\n")
    if lines and parse_header_version(lines[0]) is not None:
        lines = lines[1:]
    return "\n".join(lines).strip()


def build_render_plan(policy: IndexPolicy, *, existing: Mapping[str, str]) -> dict[str, str]:
    """Relative path -> full file content, for every file this policy renders.

    `existing` is whatever is already committed at those paths (missing ones
    simply absent); it is read only to carry action pins forward, never to
    decide what to emit.
    """
    if not policy.ci.owner:
        raise ValidationError(
            "ci.owner is not declared in .github/index-policy.json. Every generated "
            "schedule carries a cron-upstream-only guard keyed on it — a fork inherits "
            "every schedule in a workflow file and would run it against its own stale "
            "copy — so there is nothing safe to render without it."
        )
    if not policy.ci.run:
        raise ValidationError(
            "ci.run is not declared in .github/index-policy.json. It is the command "
            "every generated job uses to invoke the bot, the privileged governance job "
            "included, and it has no default: the only zero-setup spelling "
            "(`uvx ocx-indexbot`) fetches whatever was published to PyPI that morning."
        )
    if resolves_at_runtime(policy.ci.run):
        raise ValidationError(
            f"ci.run {policy.ci.run!r} resolves the bot at job start. The privileged "
            "governance job this renders holds a token that can merge a pull request and "
            "move the base branch, so which version runs there must be decided by a "
            "reviewed commit and not by a package index. Pin it: add `--frozen` (or "
            "`--locked`) to a `uv run --project <dir>` invocation so its lockfile binds, "
            "or name an exact version (`uvx --from 'ocx-indexbot==<version>' indexbot`)."
        )

    variables: dict[str, str] = {
        "owner": policy.ci.owner,
        "run": policy.ci.run,
        "cron_reconcile": policy.ci.reconcile_cron,
        "cron_stale": policy.ci.stale_cron,
        "deploy_workflow": policy.ci.deploy_workflow,
        "setup_step": f"      - uses: {policy.ci.setup}" if policy.ci.setup else "",
        "image": policy.ci.setup or DEFAULT_GITLAB_IMAGE,
        "deploy_job": "",
    }
    if policy.ci.forge == "gitlab":
        sources = {GITLAB_FILE: "gitlab/indexbot.yml"}
    else:
        if policy.ci.deploy_workflow:
            variables["deploy_job"] = render_string(
                _template("github/governance-deploy-job.yml"), variables
            )
        sources = {f"{GITHUB_DIR}/{name}": f"github/{name}" for name in _GITHUB_FILES}

    pins = scrape_pins(existing)
    return {
        path: f"{HEADER_LINE}\n{apply_pins(render_string(_template(source), variables), pins)}"
        for path, source in sources.items()
    }
