"""`ci/render.py` — the three mechanisms, each on its own.

The templates themselves are asserted in `test_ci_cmd.py` through the real
subcommand; here the substitution engine, the pin carry-forward and the drift
normalizer are exercised directly, because each one has a failure mode that
would otherwise only show up as a silently wrong workflow.
"""

from __future__ import annotations

import pytest

from ocx_indexbot.ci import render
from ocx_indexbot.errors import ValidationError
from tests.fakes import make_policy

# --- the header contract ----------------------------------------------------


def test_the_header_line_round_trips() -> None:
    assert render.parse_header_version(render.HEADER_LINE) == render.TOOL_HEADER_VERSION


@pytest.mark.parametrize(
    "line",
    ["name: validate", "# hand written", "", "# generated by ocx-catalog ci v1 — do not edit"],
)
def test_a_foreign_first_line_has_no_version(line: str) -> None:
    """ "Not ours" must be a distinct answer from "ours, version N" — it is
    what makes the first run against a hand-written tree overwrite rather than
    refuse, and what keeps another tool's generated file out of the pin
    scrape."""
    assert render.parse_header_version(line) is None


def test_a_future_version_still_parses() -> None:
    """Nothing branches per version, so a newer header is *readable* — the
    refusal to overwrite it is a decision `cli/ci_cmd.py` makes, not a parse
    failure here."""
    assert render.parse_header_version("# generated by indexbot ci v9 — do not edit") == 9


# --- placeholder substitution ------------------------------------------------


def test_substitutes_inline_placeholders() -> None:
    assert render.render_string("run: {{run}} validate", {"run": "uvx ocx-indexbot@0.2.0"}) == (
        "run: uvx ocx-indexbot@0.2.0 validate"
    )


def test_never_touches_a_github_actions_expression() -> None:
    """`${{ github.token }}` is the single most common construct in the files
    this renders. A substitution engine that ate it would produce workflows
    that look right and reference nothing."""
    template = "  GH_TOKEN: ${{ github.token }}\n  OWNER: {{owner}}"
    assert render.render_string(template, {"owner": "acme"}) == (
        "  GH_TOKEN: ${{ github.token }}\n  OWNER: acme"
    )


def test_an_empty_whole_line_placeholder_takes_its_line_with_it() -> None:
    """How an optional step disappears without a second template — and
    without leaving a blank line inside a `steps:` list, which YAML tolerates
    but a reader does not."""
    template = "    steps:\n{{setup_step}}\n      - run: echo hi"
    assert render.render_string(template, {"setup_step": ""}) == (
        "    steps:\n      - run: echo hi"
    )


def test_a_non_empty_whole_line_placeholder_renders_normally() -> None:
    template = "    steps:\n{{setup_step}}\n      - run: echo hi"
    assert render.render_string(template, {"setup_step": "      - uses: ./x"}) == (
        "    steps:\n      - uses: ./x\n      - run: echo hi"
    )


def test_an_unknown_placeholder_raises_rather_than_rendering_literally() -> None:
    with pytest.raises(ValidationError, match="unknown placeholder"):
        render.render_string("owner: {{nope}}", {})


def test_an_unknown_whole_line_placeholder_raises_too() -> None:
    """The line-drop path resolves the value first, so it must reject an
    unknown key on the same terms — otherwise a typo'd block placeholder
    would silently delete a whole job."""
    with pytest.raises(ValidationError, match="unknown placeholder"):
        render.render_string("{{nope}}", {})


# --- pin carry-forward -------------------------------------------------------


def test_an_agreeing_pin_is_carried_forward() -> None:
    committed = {"a.yml": "      - uses: actions/checkout@" + "a" * 40 + "  # v4.3.1"}
    pins = render.scrape_pins(committed)
    assert pins == {"actions/checkout": "a" * 40 + "  # v4.3.1"}
    rendered = "      - uses: actions/checkout@" + "b" * 40 + "  # v4.0.0"
    assert render.apply_pins(rendered, pins) == committed["a.yml"]


def test_two_files_disagreeing_carry_nothing() -> None:
    """There is no single answer, and picking one would silently retire the
    other. The template default wins instead."""
    pins = render.scrape_pins(
        {
            "a.yml": "      - uses: actions/checkout@" + "a" * 40,
            "b.yml": "      - uses: actions/checkout@" + "b" * 40,
        }
    )
    assert pins == {}


def test_a_mutable_ref_is_never_carried() -> None:
    """This generator emits the workflows the SHA-pinned-actions invariant
    governs. A hand-edit from a SHA to `@main` must not survive a render as
    the new pin — that would launder the edit into policy."""
    assert render.scrape_pins({"a.yml": "      - uses: actions/checkout@main"}) == {}


def test_a_mutable_ref_anywhere_poisons_the_action_everywhere() -> None:
    """Carrying the SHA from the other file would paper over exactly the
    hand-edit this rule exists to surface."""
    pins = render.scrape_pins(
        {
            "a.yml": "      - uses: actions/checkout@" + "a" * 40,
            "b.yml": "      - uses: actions/checkout@v4",
        }
    )
    assert pins == {}


def test_an_unpinned_action_keeps_the_template_default() -> None:
    rendered = "      - uses: actions/stale@" + "c" * 40
    assert render.apply_pins(rendered, {"actions/checkout": "a" * 40}) == rendered


# --- drift normalization -----------------------------------------------------


def test_a_re_pinned_action_is_not_drift() -> None:
    """A deployment's own dependency bot bumps these. Reporting that as drift
    would make `--check` red on every Dependabot PR and train the gate to be
    ignored."""
    a = render.HEADER_LINE + "\n      - uses: actions/checkout@" + "a" * 40
    b = render.HEADER_LINE + "\n      - uses: actions/checkout@" + "b" * 40 + "  # v5"
    assert render.normalize_for_drift(a) == render.normalize_for_drift(b)


def test_a_header_version_bump_is_not_drift() -> None:
    a = "# generated by indexbot ci v1 — do not edit\non:\n  pull_request:"
    b = "# generated by indexbot ci v7 — do not edit\non:\n  pull_request:"
    assert render.normalize_for_drift(a) == render.normalize_for_drift(b)


def test_a_changed_trigger_is_drift() -> None:
    a = render.HEADER_LINE + "\non:\n  pull_request:"
    b = render.HEADER_LINE + "\non:\n  pull_request_target:"
    assert render.normalize_for_drift(a) != render.normalize_for_drift(b)


def test_a_headerless_file_normalizes_without_losing_its_first_line() -> None:
    """The header strip is conditional on there being one — otherwise a
    hand-written file would silently lose `name: validate` and could compare
    equal to something it is not."""
    assert render.normalize_for_drift("name: validate\non:\n  push:").startswith("name: validate")


def test_a_sha_downgraded_to_a_mutable_ref_is_drift() -> None:
    """A-4: `scrape_pins` already refuses to *carry* a non-SHA ref, but that
    guards only what the next render writes. The drift gate that runs in CI
    on the committed file must independently see a pinned action get swapped
    for a mutable ref — including in `governance.yml`, whose `arm-auto-merge`
    job holds `contents: write` — or `--check` stays green through the
    downgrade."""
    a = render.HEADER_LINE + "\n      - uses: actions/checkout@" + "a" * 40
    b = render.HEADER_LINE + "\n      - uses: actions/checkout@main"
    assert render.normalize_for_drift(a) != render.normalize_for_drift(b)


def test_a_pin_stripped_entirely_is_drift_not_equal_to_a_blanked_pin() -> None:
    """A valid SHA used to blank down to a bare `uses: owner/repo` — with no
    `@` at all. `_USES_LINE` requires an `@` to match, so a hand-edit that
    deletes the pin outright (not merely swaps the SHA) never matches and
    passes through untouched, landing on that exact same bare text. In
    `governance.yml`'s `contents: write` job, that made "pin removed" and
    "pin present and blanked for comparison" the same string."""
    a = render.HEADER_LINE + "\n      - uses: actions/checkout@" + "a" * 40
    b = render.HEADER_LINE + "\n      - uses: actions/checkout"
    assert render.normalize_for_drift(a) != render.normalize_for_drift(b)


def test_identical_shas_with_different_trailing_comments_are_not_drift() -> None:
    """The comment beside a pin (`# v4.3.1`) is cosmetic, same as pin
    carry-forward's own rule — two files spelling it differently around the
    same SHA must still normalize equal, or every render would flag its own
    untouched pins as drift."""
    a = render.HEADER_LINE + "\n      - uses: actions/checkout@" + "a" * 40 + "  # v4.3.1"
    b = (
        render.HEADER_LINE
        + "\n      - uses: actions/checkout@"
        + "a" * 40
        + " # v4.3.1 (pinned 2026-01-01)"
    )
    assert render.normalize_for_drift(a) == render.normalize_for_drift(b)


# --- the plan ----------------------------------------------------------------


def test_an_undeclared_owner_refuses_to_render() -> None:
    """Every generated schedule carries a cron-upstream-only guard keyed on
    the owner. Rendering without one would emit a file that violates the
    invariant the generator exists to enforce."""
    with pytest.raises(ValidationError, match=r"ci\.owner"):
        render.build_render_plan(make_policy(owner=""), existing={})


def test_an_undeclared_run_refuses_to_render() -> None:
    """`ci.run` had a default — `uvx ocx-indexbot` — and it landed in
    `arm-auto-merge`, which holds a token that can move the base branch and
    squash-merge a pull request. `uvx` resolves the latest release when the
    step starts, so a deployment that never thought about this key ran
    whatever was published that morning with that token. There is no spelling
    of a default that is both zero-setup and pinned, so refusing is the only
    honest answer."""
    with pytest.raises(ValidationError, match=r"ci\.run is not declared"):
        render.build_render_plan(make_policy(run=""), existing={})


def test_a_runtime_resolved_run_refuses_to_render() -> None:
    """Declaring the floating command explicitly is no better than inheriting
    it: the generator would emit a privileged job whose version is decided by
    a package index rather than by a reviewed commit — and `indexbot ci
    --check` would then report that job clean forever, because it renders
    byte-for-byte from the same string."""
    with pytest.raises(ValidationError, match=r"resolves the bot at job start"):
        render.build_render_plan(make_policy(run="uvx ocx-indexbot"), existing={})


def test_a_lockfile_run_without_frozen_refuses_to_render() -> None:
    """The near-miss, and it was live: `uv run --project bot-tools -- indexbot`
    reads like a lockfile pin, was `ocx-sh/index`'s own `ci.run`, and is not
    one — `uv run` re-locks when the lockfile is stale against
    `pyproject.toml`, and re-locking a `[tool.uv.sources]` git source moves the
    commit. `--frozen` is what makes the lock binding."""
    with pytest.raises(ValidationError, match=r"resolves the bot at job start"):
        render.build_render_plan(
            make_policy(run="uv run --project bot-tools -- indexbot"), existing={}
        )


def test_github_renders_the_five_workflow_files() -> None:
    plan = render.build_render_plan(make_policy(), existing={})
    assert set(plan) == {
        f"{render.GITHUB_DIR}/{name}"
        for name in (
            "validate.yml",
            "governance.yml",
            "reconcile.yml",
            "pr-checks-label.yml",
            "stale.yml",
        )
    }
    assert all(text.startswith(render.HEADER_LINE) for text in plan.values())


def test_gitlab_renders_the_included_job_file_and_never_the_root() -> None:
    """C-007's hard-won rule, carried over from `@ocx-sh/catalog`: owning the
    root `.gitlab-ci.yml` would either clobber whatever else the operator runs
    or force this tool to parse and merge it."""
    plan = render.build_render_plan(make_policy(forge="gitlab"), existing={})
    assert set(plan) == {".gitlab-ci/indexbot.yml"}
    assert ".gitlab-ci.yml" not in plan


@pytest.mark.parametrize("forge", ["github", "gitlab"])
def test_no_generated_file_carries_a_hand_rolled_root_pathspec(forge: str) -> None:
    """The pathspec that tells a package root from a CAS object used to be
    rendered into the validate job, from `name_segments`, as a `git diff`
    argument. It was the one thing in these files that was silently wrong on
    any index not two segments deep — and, being YAML, it was also untestable:
    dropping its `:(glob)` made every announce PR fail this required check,
    and softening its `...` to `..` re-verified stale copies of roots the PR
    never touched.

    `indexbot validate-pr` derives it from the deployment's own policy at run
    time now, so a re-render can no longer be what makes an index correct. The
    property to hold is therefore the ABSENCE: no generated file may reconstruct
    the pathspec, on either forge."""
    plan = render.build_render_plan(make_policy(forge=forge), existing={})
    for text in plan.values():
        code = "\n".join(line for line in text.split("\n") if not line.strip().startswith("#"))
        assert ":(glob)" not in code
        assert "git diff" not in code


def test_the_deploy_job_is_absent_unless_a_deploy_workflow_is_named() -> None:
    """Publishing is a hosting choice. A generator that named one would make
    every index deploy the way the public one happens to."""
    without = render.build_render_plan(make_policy(), existing={})
    assert "\n  deploy-on-merge:\n" not in without[f"{render.GITHUB_DIR}/governance.yml"]

    with_deploy = render.build_render_plan(
        make_policy(deploy_workflow="render-deploy.yml"), existing={}
    )
    governance = with_deploy[f"{render.GITHUB_DIR}/governance.yml"]
    assert "\n  deploy-on-merge:\n" in governance
    assert 'gh workflow run "render-deploy.yml" --repo' in governance


def test_deploy_workflow_is_quoted_at_its_shell_call_site() -> None:
    """`deploy_workflow` renders unquoted-by-template into `gh workflow run
    {{deploy_workflow}}` — a job holding `actions: write` + `contents:
    write` — so a value with an embedded space would become more than one
    argv word to `gh`. `core/policy.py`'s `_DEPLOY_WORKFLOW_RE` already
    closes that off at parse time, but the call site is quoted too, so a
    future template edit that reintroduces the unquoted form is caught here
    rather than relying solely on the grammar never having a gap."""
    plan = render.build_render_plan(make_policy(deploy_workflow="render-deploy.yml"), existing={})
    governance = plan[f"{render.GITHUB_DIR}/governance.yml"]
    assert 'if gh workflow run "render-deploy.yml" --repo "$REPO" --ref main; then' in governance
    assert "if gh workflow run render-deploy.yml --repo" not in governance


def test_an_empty_setup_leaves_no_step_behind() -> None:
    plan = render.build_render_plan(make_policy(setup=""), existing={})
    validate = plan[f"{render.GITHUB_DIR}/validate.yml"]
    assert "uses: ./" not in validate
    assert "\n\n      - name: Determine changed" not in validate, "no blank line left over"


def test_gitlab_falls_back_to_a_uv_image_when_setup_is_empty() -> None:
    plan = render.build_render_plan(make_policy(forge="gitlab", setup=""), existing={})
    assert f"image: {render.DEFAULT_GITLAB_IMAGE}" in plan[".gitlab-ci/indexbot.yml"]


def test_gitlab_uses_the_declared_setup_as_its_image() -> None:
    plan = render.build_render_plan(
        make_policy(forge="gitlab", setup="registry.example/ci:1"), existing={}
    )
    assert "image: registry.example/ci:1" in plan[".gitlab-ci/indexbot.yml"]
